version: '3.9'
services:
  gui:
    image: pattern-gui:latest
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    user: "${UID}:${GID}"
    working_dir: /home/$USER
    command: /bin/bash -c "xeyes"