version: '3.9'
services:
  xeyes3:
    tty: true
    build:
      context: ../.docker
      dockerfile: Dockerfile
    image: xeyes/patternc:latest
    container_name: xeyes_containerc
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /home/$USER:/home/$USER
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    user: "${UID}:${GID}"
    network_mode: host