version: '3.9'
services:
  gui:
    build: 
      context: ../.docker
      dockerfile: Dockerfile
      args:
        - USERNAME=main
        - GROUPNAME=main
        - PASSWORD=main
        - UID=1000
        - GID=1000
    image: pattern-gui:ver2
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: $HOME/.Xauthority
        target: /home/main/.Xauthority.copy
      - ..:/home/main/ws
    network_mode: host
    command: /bin/bash -c "cd ~; cp .Xauthority.copy .Xauthority; chown main:main .Xauthority"