version: '3.9'
services:
  gui:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=main
        - GROUPNAME=main
        - PASSWORD=main
        - UID=1000
        - GID=1000
    image: pattern-gui:ver1
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash -c "xeyes"
    