version: '3.9'
services:
  gui:
    image: pattern-gui:latest
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: $HOME/.Xauthority
        target: /root/.Xauthority.copy
    network_mode: host
    command: /bin/bash -c "cd ~; cp .Xauthority.copy .Xauthority; chown root:root .Xauthority; xeyes"