version: '3.9'
services:
  gui:
    image: pattern-gui:latest
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: $HOME/.Xauthoriy
        target: /root/.Xauthoriy.copy
    command: /bin/bash -c "cp /root/.Xauthoriy.copy /root/.Xauthority; chown root:root /root/.Xauthority; xeyes"