version: '3.9'
services:
  gui:
    image: pattern-gui:latest
    container_name: gui
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthoriy:/root/.Xauthoriy.copy
    network_mode: host
    command: /bin/bash -c "cd; cp .Xauthoriy.copy .Xauthority; chown root:root .Xauthority; xeyes"